apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: notification-service-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/BenHampton/k8s-helm-event-driven-microservices
    targetRevision: main
    path: notification-service/helm    # location of helm charts
    helm:
      releaseName: notification-service
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true               # delete resources removed from Git
      selfHeal: true            # revert manual cluster changes
    syncOptions:
      - CreateNamespace=false   # namespaces already exist