server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:orders}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:password}
  liquibase:
    enabled: false
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  jpa:
    show-sql: true

logging:
  level:
    com.k8sdemo.order: DEBUG