apiVersion: v1
kind: Service
metadata:
  name: orders-db-prod    # name order-service connects to
  namespace: prod
spec:
  type: ExternalName
  externalName: orders-db-prod.data.svc.cluster.local   # RDS endpoint, e.g. orders.abc123.us-east-1.rds.amazonaws.com

---

apiVersion: v1
kind: Service
metadata:
  name: notifications-db
  namespace: prod
spec:
  type: ExternalName
  externalName: notifications-db-prod.data.svc.cluster.local

---

apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: prod
spec:
  type: ExternalName
  externalName: rabbitmq-prod.data.svc.cluster.local